### ISSUE TITLE
doesn't properly combine requests into 1

### ISSUE THREAD

**Issue by Dieterbe** [raintank/graphite-raintank#11] opened 2015-12-07 20:54 UTC
need to further look into this once i can work out some consolidateBy related kinks.

but this patch

```
diff --git a/metric_tank/http.go b/metric_tank/http.go
index a6249a9..21c9a0f 100644
--- a/metric_tank/http.go
+++ b/metric_tank/http.go
@@ -40,6 +40,7 @@ func get(metaCache *MetaCache, aggSettings []aggSetting) http.HandlerFunc {
 func Get(w http.ResponseWriter, req *http.Request, metaCache *MetaCache, aggSettings []aggSetting) {
        pre := time.Now()
        values := req.URL.Query()
+       log.Debug(fmt.Sprintf("INCOMING %q", values.Get("target")))

        consolidateBy := values.Get("consolidateBy")

```

results in
![multi](https://cloud.githubusercontent.com/assets/20774/11639424/a5497274-9d91-11e5-9725-b8a485cd9058.png)

should be 3 targets in 1 req. seeing 2 targets in 2 different requests.

per http://graphite-api.readthedocs.org/en/latest/finders.html#fetching-multiple-paths-at-once we're not leveraging the concurrency of fetch_multi right now, instead our responses are slower cause it fetches the node data one by one.

**Comment by Dieterbe** [comment] 2015-12-08 23:07
It looks like fetch_multi is not behaving as expected. it's being called multiple times with a single node each time, even when we request multiple targets from graphite-api in 1 request.  it's kind of hard to believe but it looks like fetch_multi in graphite-api never worked properly to begin with? ( i think i remember it working fine when i was doing graphite-influxdb though)

anyway, there's been some interesting work upstream, such as https://github.com/brutasse/graphite-api/pull/119
and some followup PR's

**Comment by woodsaj** [comment] 2016-02-25 10:07
@diterbe i dont think this is a problem anymore. The cause of the problem was the bug in graphite-api.  The fixes for this were merged into our fork.

Does your testing today confirm that a single graphite request results in a single MT request?

**Closed as completed** 2016-04-26 07:31 UTC
